# 4.5 선형대수

In [1]:
import numpy as np

In [2]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])

In [3]:
y=np.array([[6.,23,],[-1,7],[8,9]])

In [4]:
print(x);print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [5]:
x.dot(y) #x%*%y (2X3)X(3X2), dot은 행렬의 곱셈을 해주는 함수

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x,np.ones(3)) #(2X3)X(3X1)  -> np.ones(3)이라는 일벡터와 곱해서 각 행의 합이 나옴.

array([ 6., 15.])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [6]:
from numpy.linalg import inv,qr #numpy.linalg은 행렬의 분할 역행렬,행렬식 포함

In [7]:
X=np.random.randn(5,5)

In [8]:
X

array([[-0.81866638, -0.72349959,  0.31051178, -2.18293541, -0.47490506],
       [-0.65360388, -1.00610377,  0.71069257, -0.46432317,  0.34068235],
       [ 2.01005716, -0.43384596,  0.94398703, -0.579982  ,  0.44957159],
       [-0.74029688,  0.5698063 , -1.08744724, -1.21168672,  0.07619872],
       [-1.30903124,  0.16604073, -0.47621666, -0.68204118, -0.96693226]])

In [9]:
mat=X.T.dot(X) #X^2

In [10]:
inv(mat)

array([[ 1098.13621078, -3529.90870061, -3221.1403134 ,   498.75506236,
         -878.78301618],
       [-3529.90870061, 11350.15852149, 10356.7241618 , -1603.92229749,
         2824.56362482],
       [-3221.1403134 , 10356.7241618 ,  9450.78583248, -1463.45597956,
         2577.23935241],
       [  498.75506236, -1603.92229749, -1463.45597956,   226.83080664,
         -399.23513   ],
       [ -878.78301618,  2824.56362482,  2577.23935241,  -399.23513   ,
          704.24119804]])

In [11]:
mat.dot(inv(mat)) #mat의 역행렬 X mat 행렬  -> 항등행렬

array([[ 1.00000000e+00, -1.20949958e-12,  3.32468611e-13,
        -7.13625949e-14, -1.83184211e-13],
       [ 8.48223389e-13,  1.00000000e+00, -5.52382558e-12,
         6.78900517e-13, -8.82538831e-13],
       [ 8.04842911e-13, -3.50481177e-12,  1.00000000e+00,
         4.81038272e-13, -1.17083938e-12],
       [ 4.15716233e-13,  3.17533708e-13, -2.71804709e-12,
         1.00000000e+00, -4.44135634e-13],
       [-4.00817610e-13, -1.90085727e-12, -8.08926448e-14,
         3.66936765e-14,  1.00000000e+00]])

In [12]:
q,r=qr(mat) #QR분해라고 한다 나도 잘모름?

https://ko.wikipedia.org/wiki/QR_분해 #이럴땐 위키!

In [13]:
r

array([[-8.61274433e+00,  5.18803776e-01, -3.44518138e+00,
        -4.91200197e+00, -3.00519064e+00],
       [ 0.00000000e+00, -3.26098120e+00,  2.83281809e+00,
        -4.67036917e+00,  6.45752376e-02],
       [ 0.00000000e+00,  0.00000000e+00, -5.74497487e-01,
        -3.95387486e+00, -1.38615696e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.41820036e+00, -8.05259333e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.49626415e-04]])

In [14]:
q

array([[-0.8591158 , -0.05654039,  0.33503007,  0.31361761, -0.21936745],
       [ 0.03034287, -0.6318422 ,  0.26719965,  0.17695554,  0.70508569],
       [-0.30271039,  0.57985276, -0.37672441,  0.12775184,  0.64334702],
       [-0.31518449, -0.50842936, -0.7685869 , -0.20371663, -0.09965963],
       [-0.26462146,  0.05337596,  0.28933042, -0.90139322,  0.17579721]])

## 자주 사용하는 numpy.linalg함수

$numpy.diag$  #대각원소만 뽑기

$numpy.dot$   #행렬 곱

$numpy.trace$  #trace 계산

$numpy.linalg.det$   #행렬식 계산

numpy.linalg.eig  #고유값과 고유벡터

$numpy.linalg.inv$   #inverse함수

numpy.linalg.pinv   

numpy.linalg.qr   #qr분해

numpy.linalg.svd   #특이값 분해

$numpy.linalg.solve$ #Ax=b 를 만족하는 x구함

$numpy.linalg.lstsq$ #y=xb를 만족하는 최소제곱해를 구함

In [15]:
x=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

In [16]:
y=np.array([[4.,5.,6.],[7.,8.,9.],[1.,2.,3.]])

In [17]:
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
y

array([[4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.]])

문제!

1.행렬 x의 대각선 원소를 반환하시오

2.행렬 x X y를 구하시오

3.행렬 x의 대각선 원소의 합을 구하시오(trace이용)

4.det(y)를 구하시오

In [21]:
np.diag(x)

array([1., 5., 9.])

In [22]:
np.dot(x,y)   #x.dot(y)도 가능

array([[ 21.,  27.,  33.],
       [ 57.,  72.,  87.],
       [ 93., 117., 141.]])

In [23]:
np.trace(x)

15.0

In [25]:
np.linalg.det(y)

-9.51619735392994e-16

# 4.6 난수 생성

In [26]:
samples =np.random.normal(size=(4,4))

In [27]:
samples

array([[ 0.66085004, -0.0989032 , -0.80420457, -1.2331293 ],
       [ 2.2543077 , -0.09731639,  1.13335452, -0.36179956],
       [-2.29864921,  0.30857131,  0.99382589,  0.71221777],
       [-0.1301532 ,  1.49210613, -0.56600867,  0.21355051]])

In [28]:
from random import normalvariate

In [29]:
N=1000000

In [30]:
%timeit samples =[normalvariate(0,1) for _ in range(N)]

708 ms ± 13.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%timeit np.random.normal(size=N) #위에 있는 파이선 내장 모듈보다 속도가 빠름을 알 수 있음

24.4 ms ± 580 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 4.7 계단 오르내리기 예제

In [32]:
import random
position =0
walk =[position]
steps =1000
for i in range(steps):           #현재 값에 1 또는 -1을 랜덤으로 진행
    step =1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [40]:
walk

array([ -1,  -2,  -1,   0,  -1,   0,  -1,   0,  -1,   0,   1,   0,   1,
         0,  -1,  -2,  -1,  -2,  -1,   0,  -1,  -2,  -1,  -2,  -1,   0,
        -1,  -2,  -3,  -2,  -3,  -2,  -1,   0,  -1,   0,   1,   2,   3,
         4,   3,   4,   3,   2,   1,   2,   3,   2,   1,   0,  -1,   0,
         1,   0,  -1,  -2,  -3,  -2,  -3,  -4,  -3,  -2,  -1,   0,  -1,
         0,   1,   0,   1,   2,   3,   2,   3,   2,   3,   4,   5,   6,
         7,   6,   5,   4,   3,   2,   1,   2,   3,   4,   5,   4,   5,
         4,   5,   4,   5,   4,   3,   4,   3,   2,   3,   2,   1,   0,
         1,   2,   3,   2,   1,   2,   3,   4,   3,   4,   5,   6,   7,
         6,   5,   4,   5,   6,   5,   4,   5,   6,   5,   4,   3,   2,
         3,   2,   1,   2,   3,   4,   5,   4,   5,   4,   5,   6,   5,
         6,   5,   4,   5,   4,   3,   4,   5,   6,   7,   8,   7,   8,
         9,  10,  11,  10,   9,  10,   9,  10,   9,  10,   9,  10,   9,
         8,   9,  10,   9,   8,   7,   6,   5,   4,   5,   6,   

In [33]:
nsteps=1000

In [43]:
draws= np.random.randint(0,2,size=nsteps)   #0과 1 중 랜덤하게 하나를 뽑는 과정을 1000번 반복
draws

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,

In [44]:
steps=np.where(draws>0,1,-1)   #draws의 0은 -1로, 1은 1로
steps

array([ 1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1, -1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1, -1,  1, -1,  1,
       -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1,
        1, -1,  1,  1, -1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1,  1, -1,
        1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1,
       -1,  1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1,
       -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,
       -1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,
       -1, -1, -1,  1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1,
        1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,
        1,  1,  1, -1, -1

In [48]:
walk=steps.cumsum()  #누적합을 통해 첫 시작점부터 어디까지 갔는지

In [49]:
walk.min()

-33

In [50]:
walk.max()

15

In [51]:
(np.abs(walk)>=10).argmax()

89

In [53]:
walk[89]

10

## 4.7.1 계단 한번에 오르내리기 시뮬레이션하기

In [54]:
nwalks=5000

In [55]:
nsteps=1000

In [56]:
draws= np.random.randint(0,2, size=(nwalks, nsteps))

In [57]:
draws

array([[1, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 1, ..., 0, 1, 1]])

In [58]:
steps =np.where(draws>0,1,-1)

In [59]:
walks = steps.cumsum(1)       #행끼리

In [60]:
walks

array([[  1,   2,   1, ...,  16,  15,  14],
       [ -1,  -2,  -1, ...,   8,   9,   8],
       [ -1,   0,  -1, ...,  54,  53,  54],
       ...,
       [ -1,   0,   1, ...,  -6,  -5,  -4],
       [ -1,  -2,  -3, ..., -36, -35, -34],
       [ -1,  -2,  -1, ...,   2,   3,   4]], dtype=int32)

In [61]:
walk.max()

15

In [62]:
walk.min()

-33

In [63]:
hits30 =(np.abs(walks)>=30).any(1)  

In [64]:
hits30

array([ True, False,  True, ...,  True,  True, False])

In [65]:
hits30.sum()

3381

In [66]:
crossing_times= (np.abs(walks[hits30])>=30).argmax(1)

In [67]:
crossing_times.mean()

501.3874593315587

In [68]:
steps= np.random.normal(loc=0,scale=0.25,size=(nwalks,nsteps))

In [69]:
steps

array([[ 0.09768309,  0.09080566, -0.19868232, ...,  0.394935  ,
         0.18636047, -0.46608868],
       [ 0.22258177,  0.12292876, -0.39997341, ...,  0.07770477,
         0.22585734,  0.09280584],
       [-0.39616456, -0.08206892,  0.13155463, ...,  0.27097183,
        -0.27620487, -0.27891832],
       ...,
       [-0.08995759,  0.14821293,  0.33469141, ...,  0.10327188,
        -0.31368137, -0.07213925],
       [-0.29180818,  0.0162736 , -0.2521404 , ..., -0.11550374,
        -0.05811038,  0.03746045],
       [-0.26514227, -0.05416042,  0.05777805, ..., -0.21558569,
        -0.07828117,  0.26941919]])